### ISSUE TITLE
Node.ping always returns :pang

### ISSUE THREAD

**Issue by simonprev** [utkarshkukreti/ex_top#1]
I realize that maybe my issue is not directly related to `ex_top` but when I follow the steps in the Readme, the `Node.ping/1` always returns `:pang`. Do I have anything to do so that `:nonode@nohost` can be "pinged". Do I have to have a named process?

I’m a bit of a newbie in the erlang VM world :expressionless:

**Comment by utkarshkukreti** [comment]
You need to give the other node a `--name` or `--sname` and a `--cookie` and then pass that name to `./ex_top`, for example:

```
$ iex --sname foo --cookie foo
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(foo@Utkarshs-MacBook-Pro)1>
```

and then

```
$ ./ex_top foo@Utkarshs-MacBook-Pro --cookie foo
```

**Comment by simonprev** [comment]
Oh alright! Thanks for the quick response! :+1:

**Comment by utkarshkukreti** [comment]
I added a better message for this error in 61ee345239b6a9806e5e1d508255a87a7c1d2105.
